markdown: pandoc
pandoc:
    skip: false
    bundle_permalink: ':slug.:output_ext'
    papersize: 'a5paper'
    sheetsize: 'a4paper'
    imposition: true
    binder: true
    covers_dir: 'images/covers'
    flags: '--smart -V lang=es
            --section-divs --email-obfuscation=references'
    outputs:
        pdf: '-V fontsize=8pt,twoside
                -V documentclass=book
                -V geometry=hcentering
                -V geometry=bindingoffset=5mm
                --latex-engine=xelatex
                --include-in-header=_layouts/header.tex
                --include-before-body=_layouts/license.tex'
        epub: '--epub-chapter-level=2'
        mediawiki:
        rst:
        latex: '-V fontsize=8pt,twoside
                  -V documentclass=book
                  -V geometry=hcentering
                  -V geometry=bindingoffset=1cm
                  --latex-engine=xelatex
                  --table-of-contents
                  --include-in-header=_layouts/header.tex
                  --include-before-body=_layouts/license.tex'

destination: ./site/enlamarea.net
layouts_dir:  ./_layouts
plugins_dir:  ./_plugins

exclude: [ tmp ]

permalink: ":title.html"

lsi: false

torrent:
  file: enlamarea.torrent
