# Site's metadata
logo: assets/en_la_marea_logo.png
title: En la Marea
tagline:
author: Camila Pérez Schunk
email: cami@enlamarea.net
lang: es

markdown: pandoc
pandoc:

    skip: false
    bundle_permalink: ':slug.:output_ext'
    papersize: 'a5paper'
    sheetsize: 'a4paper'
    imposition: true
    binder: true
    covers_dir: 'images/covers'
    flags: '--smart -V lang=es
            --section-divs --email-obfuscation=references'
    outputs:
        pdf: '--toc
              -V fontsize=10pt,twoside
              -V documentclass=book
              -V geometry=hcentering
              -V geometry=bindingoffset=5mm
              -V links-as-notes=true
              -V subparagraph
              --latex-engine=xelatex
              --include-in-header=_layouts/header.tex
              --include-before-body=_layouts/license.tex'
        epub: '-V lang=es --epub-chapter-level=2'

destination: ./site/enlamarea.net

jekyll-archives:
  enabled:
    - categories
  permalinks:
    category: :name.html

exclude: [ tmp ]

permalink: ":title.html"

lsi: false

torrent:
  file: enlamarea.torrent

